function [fitresult, gof] = createFit(curveX, curveY)
%CREATEFIT(CURVEX,CURVEY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : curveX
%      Y Output: curveY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Apr-2018 15:11:31


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( curveX, curveY );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [807 1.69575554089028 1.37024415631194 793.236796659799 -1.69575554089028 0.511534455455808 711.716446022417 -0.678302216356113 0.306718820891376];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'curveY vs. curveX', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel curveX
% ylabel curveY
% grid on


